### ISSUE TITLE
Ferry ignore closed bridge

### ISSUE THREAD

**Issue by t1a2l** [boformer/MovableBridge#5]
placed the ferry path and line over the bridge, the ferry ignores the bridge and go through it, i seen it stop before the bridge only once in a while.  
my output log is attached. (cars and buses and people stop when they are suppsoed too).
[output_log.txt](https://github.com/boformer/MovableBridge/files/6679745/output_log.txt)
![image](https://user-images.githubusercontent.com/17047560/122627046-e97eee80-d0b5-11eb-9fc3-495454c49844.png)

**Comment by boformer** [comment]
ferry is probably so low that it can pass under the bridge

**Comment by t1a2l** [comment]
you were right
